apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.backend.env.DATABASE_URL | quote }}
            - name: GEMINI_API_KEY
              value: {{ .Values.backend.env.GEMINI_API_KEY | quote }}
            - name: GEMINI_MODEL
              value: {{ .Values.backend.env.GEMINI_MODEL | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.backend.env.CORS_ORIGINS | quote }}
      restartPolicy: Always
